#ifndef COMMON_SECTION_PERMISSIONS_HPP
#define COMMON_SECTION_PERMISSIONS_HPP

#include <vector>
#include <string>
#include <LIEF/LIEF.hpp>


std::vector<std::pair<std::string, LIEF::PE::Section::CHARACTERISTICS>> common_sections_permissions = {
    {".text", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_EXECUTE | LIEF::PE::Section::CHARACTERISTICS::CNT_CODE},
    {".data", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_WRITE | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".rdata", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".rsrc", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".reloc", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA | LIEF::PE::Section::CHARACTERISTICS::MEM_DISCARDABLE},
    {".bss", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_WRITE | LIEF::PE::Section::CHARACTERISTICS::CNT_UNINITIALIZED_DATA},
    {".tls", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_WRITE | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".idata", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".edata", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".debug", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".pdata", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    
    // Additional sections
    {".crt", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_WRITE | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".tls$", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_WRITE | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".import", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".textbss", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::MEM_WRITE | LIEF::PE::Section::CHARACTERISTICS::CNT_UNINITIALIZED_DATA},
    {".sxdata", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".arch", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".bind", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".cormeta", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".drectve", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".gfids", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
    {".gljmp", LIEF::PE::Section::CHARACTERISTICS::MEM_READ | LIEF::PE::Section::CHARACTERISTICS::CNT_INITIALIZED_DATA},
};





#endif // COMMON_SECTION_PERMISSIONS_HPP
